services:
  fragments:
    image: ${DOCKER_REPO}:${DOCKER_TAG}
    init: true
    ports:
      - '80:8080'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - HTPASSWD_FILE=tests/.htpasswd
      - AWS_REGION=us-east-1
      # Use whatever LOG_LEVEL is set to, or `info` as a default if not set
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Allow the following variables to be forwarded into the container from the env if set
      - AWS_COGNITO_POOL_ID
      - AWS_COGNITO_CLIENT_ID
      # The S3 Bucket to use, default to `fragments` if missing
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-fragments}
      - API_URL
      - TINI_SUBREAPER=true
      - AWS_DYNAMODB_TABLE_NAME=${AWS_DYNAMODB_TABLE_NAME:-fragments}
